<?php

/**
 * @file
 * The farmOS Layout Builder module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_nfa_lb_preprocess_asset__cfr__full(&$variables) {
  // Assets have a default 2 column layout that is set in
  // farm_ui_theme_preprocess_asset__full(). This more specific hook prevents
  // calling the general asset preprocess hook and allows us to configure the
  // CFR layout with Layout Builder.

  // Don't show the asset type.
  unset($variables['content']['type']);

  $variables['#attached']['library'][] = 'farm_nfa_lb/styles';

}
