<?php

/**
 * @file
 * The farmOS Layout Builder module.
 */

/**
 * Implements hook_preprocess_HOOK() for case 'asset__cfr__full'.
 */
function farm_nfa_lb_preprocess_asset__cfr(&$variables) {
  $variables['#attached']['library'][] = 'farm_nfa_lb/styles';
}

/**
 * Implements hook_preprocess_HOOK() for case 'plan__natural__full'.
 */
function farm_nfa_lb_preprocess_plan__natural__full(&$variables) {
  $variables['#attached']['library'][] = 'farm_nfa_lb/styles';
}
