<?php
/**
 * @file
 * Provides alters and hooks for the farm_ui_layout_builder module.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function farm_ui_layout_builder_theme_registry_alter(&$theme_registry) {
  // Override the farm_ui layout to use layout builder instead.
  if (isset($theme_registry['asset__full']['preprocess functions'])) {
    $theme_registry['asset__full']['preprocess functions'] = array_filter($theme_registry['plan__full']['preprocess functions'], fn($f) => $f != 'farm_ui_theme_preprocess_asset__full');
  }
  if (isset($theme_registry['log__full']['preprocess functions'])) {
    $theme_registry['log__full']['preprocess functions'] = array_filter($theme_registry['plan__full']['preprocess functions'], fn($f) => $f != 'farm_ui_theme_preprocess_log__full');
  }
  if (isset($theme_registry['plan__full']['preprocess functions'])) {
    $theme_registry['plan__full']['preprocess functions'] = array_filter($theme_registry['plan__full']['preprocess functions'], fn($f) => $f != 'farm_ui_theme_preprocess_plan__full');
  }
}

/**
 * Implements hook_preprocess_HOOK() for layout builder farmOS integration.
 */
function farm_ui_layout_builder_preprocess_page(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if (in_array($route_name, \Drupal::service('lb_routing.service')->getEnabledRoutes())) {
    $variables['#attached']['library'][] = 'farm_ui_layout_builder/layout';
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Remove gin toolbar menu alter so the farmOS one is the one winning.
 */
function farm_ui_layout_builder_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'toolbar_alter') {
    unset($implementations['gin_toolbar']);
  }
}
