<?php
/**
 * Implements hook_form_FORM_ID_alter() on behalf of 'user_form'.
 */
function farm_nfa_forest_form_asset_forest_add_form_alter(array &$form) {
  $form['forest_type']['widget']['#multiple'] = FALSE;
  $form['forest_type']['widget']['#options'] = [
    'natural' => t('Natural stand'),
    'plantation' => t('Plantation'),
    'none' => t('- None -'),
  ];
  $form['forest_type']['widget']['#default_value'] = 'none';
  $form['group_natural_forest_stand']['#states'] = [
    'visible' => [
      [':input[name="forest_type"]' => ['value' => 'natural']],
    ],
  ];
  $form['group_plantation_stand']['#states'] = [
    'visible' => [
      [':input[name="forest_type"]' => ['value' => 'plantation']],
    ],
  ];
}
