<?php
/**
 * @file
 * Provides alters and hooks for the farm nfa forest module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for 'asset_forest_add_form'.
 */
function farm_nfa_forest_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $is_new_form = $form_id == 'asset_forest_add_form';
  $is_edit_form = $form_id == 'asset_forest_edit_form';
  if ($is_new_form || $is_edit_form) {
    $form['purpose']['widget']['#ajax']['#limit_validation_errors'] = [];
    $form['forest_type']['widget']['#multiple'] = FALSE;
    $form['forest_type']['widget']['#options'] = [
      'natural' => t('Natural stand'),
      'plantation' => t('Plantation'),
      '' => t('- None -'),
    ];
    if($is_new_form){
      $form['forest_type']['widget']['#default_value'] = '';
    }
    $form['group_natural_forest_stand']['#states'] = [
      'visible' => [
        [':input[name="forest_type"]' => ['value' => 'natural']],
      ],
    ];
    $form['group_plantation_stand']['#states'] = [
      'visible' => [
        [':input[name="forest_type"]' => ['value' => 'plantation']],
      ],
    ];
  }
}
