<?php

/**
 * @file
 * Provides alters and hooks for the farm nfa module.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Url;
use Drupal\farm_nfa\Form\FarmNfaQuantityInlineForm;
use Drupal\log\Entity\LogInterface;

/**
 * Implements hook_entity_type_alter().
 */
function farm_nfa_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['plan']->setLinkTemplate('management', '/plan/{plan}/management');
  $entity_types['plan']->setLinkTemplate('budget', '/plan/{plan}/budget');
  $entity_types['plan']->setLinkTemplate('inventory', '/plan/{plan}/inventory');
  $entity_types['plan']->setLinkTemplate('harvest', '/plan/{plan}/harvest');
  $entity_types['quantity']->setHandlerClass('inline_form', FarmNfaQuantityInlineForm::class);
}

/**
 * Implements hook_entity_type_build().
 */
function farm_nfa_entity_type_build(array &$entity_types) {
  /** @var \Drupal\Core\Config\Entity\ConfigEntityType[] $entity_types */
  $entity_types['plan']->setHandlerClass('local_task_provider', ['default' => 'Drupal\farm_nfa\Menu\NfaEntityLocalTaskProvider']);
}

/**
 * Implements hook_css_alter().
 */
function farm_nfa_css_alter(&$css) {
  // Workaround to display the css of the offcanvas dialog in a way Gin/Claro
  // don't mess with the styles.
  $options = \Drupal::routeMatch()->getRouteObject()->getOptions();
  if (isset($options['parameters']) && !empty($options['parameters']['task_route'])) {
    unset($css['core/misc/dialog/off-canvas.base.css']);
    unset($css['core/misc/dialog/off-canvas.button.css']);
    unset($css['core/misc/dialog/off-canvas.css']);
    unset($css['core/misc/dialog/off-canvas.details.css']);
    unset($css['core/misc/dialog/off-canvas.dropbutton.css']);
    unset($css['core/misc/dialog/off-canvas.form.css']);
    unset($css['core/misc/dialog/off-canvas.layout.css']);
    unset($css['core/misc/dialog/off-canvas.motion.css']);
    unset($css['core/misc/dialog/off-canvas.reset.css']);
    unset($css['core/misc/dialog/off-canvas.table.css']);
    unset($css['core/misc/dialog/off-canvas.theme.css']);
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function farm_nfa_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if (!$entity instanceof LogInterface) {
    return;
  }
  if (!$entity->access('update')) {
    return;
  }
  $options = \Drupal::routeMatch()->getRouteObject()->getOptions();
  if (isset($options['parameters']) && !empty($options['parameters']['task_route'])) {
    // Replace the edit operation.
    $operations['edit'] = [
      'title' => t('Edit'),
      'url' => Url::fromRoute($options['parameters']['task_route'],
        ['plan' => \Drupal::routeMatch()->getRawParameter('plan')],
        [
          'attributes' => [
            'class' => ['use-ajax'],
            'data-dialog-type' => 'dialog',
            'data-dialog-renderer' => 'off_canvas',
            'data-dialog-options' => Json::encode([
              'width' => '50%',
             ]),
           ],
          'query' => ['log' => $entity->id()]
        ]
      ),
    ];
    // Replace the delete operation.
    if ($operations['delete']) {
      /** @var \Drupal\Core\Url $delete_url */
      $delete_url = $operations['delete']['url'];
      $operations['delete']['url'] = Url::fromRoute(
        $delete_url->getRouteName(),
        $delete_url->getRouteParameters(),
        $delete_url->getOptions() + [
          'attributes' => [
            'class' => ['use-ajax'],
            'data-dialog-type' => 'dialog',
            'data-dialog-renderer' => 'off_canvas',
            'data-dialog-options' => Json::encode([
              'width' => '50%',
            ]),
          ],
        ],
      );
    }

  }
}

/**
 * Implements hook_preprocess_menu__toolbar__gin().
 */
function farm_nfa_preprocess_menu__toolbar__gin(&$variables) {
  if (!empty($variables['items'])) {
    // Unset locations menu item.
    if (array_key_exists('farm.locations', $variables['items'])) {
      unset($variables['items']['farm.locations']);
    }
    if (array_key_exists('farm.records', $variables['items']) && !empty($variables['items']['farm.records']['below'])) {
      $records_below = $variables['items']['farm.records']['below'];
      // Unset block and land menu items inside of assets menu.
      if (array_key_exists('views_view:views.farm_asset.page', $records_below) && !empty($records_below['views_view:views.farm_asset.page']['below'])) {
        unset($variables['items']['farm.records']['below']['views_view:views.farm_asset.page']['below']['farm.asset.type:farm.asset.block']);
        unset($variables['items']['farm.records']['below']['views_view:views.farm_asset.page']['below']['farm.asset.type:farm.asset.land']);
      }

      // Unset quantity menu item.
      if (array_key_exists('views_view:views.farm_quantity.page', $records_below)) {
        unset($variables['items']['farm.records']['below']['views_view:views.farm_quantity.page']);
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function farm_nfa_preprocess_block__local_actions_block(&$variables) {
  // Hide action buttons in dashboard page.
  if (\Drupal::routeMatch()->getRouteName() == 'farm.dashboard') {
    foreach ($variables['content'] as $key => $action) {
      $action_route = substr($key, 0, 12);
      // Check that action route belongs to farm actions.
      if ($action_route == 'farm.actions') {
        $variables['content'][$key]['#access'] = FALSE;
      }
    }
  }
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function farm_nfa_menu_local_actions_alter(&$local_actions) {
  unset($local_actions['entity.asset.add_page']);
  unset($local_actions['entity.log.add_page']);
  unset($local_actions['entity.plan.add_page']);
  unset($local_actions['farm.actions:farm.add.log.bundle']);
}

/**
 * Implements hook_farm_dashboard_panes().
 */
function farm_nfa_farm_dashboard_panes() {
  return [
    'dashboard_assets_search' => [
      'title' => t('Assets'),
      'block' => 'farm_nfa_dashboard_search_form_block',
      'region'  => 'first',
      'args'  => [
        'route' => 'entity.asset.collection',
        'entity_type' => 'asset'
      ],
    ],
    'dashboard_plans_search' => [
      'title' => t('Plans'),
      'block' => 'farm_nfa_dashboard_search_form_block',
      'region'  => 'second',
      'args'  => [
        'route' => 'entity.plan.collection',
        'entity_type' => 'plan'
      ],
    ],
  ];
}

/**
 * Implements hook_theme_registry_alter().
 */
function farm_nfa_theme_registry_alter(&$theme_registry) {
  // Override the farm_ui layout to use layout builder instead.
  if (isset($theme_registry['plan__full']['preprocess functions'])) {
    $theme_registry['plan__full']['preprocess functions'] = array_filter($theme_registry['plan__full']['preprocess functions'], fn($f) => $f != 'farm_ui_theme_preprocess_plan__full');
  }
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function farm_nfa_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'log') {
    $fields['location']->addConstraint('DuplicateReference');
  }
}
