<?php
/**
 * @file
 * Date range picker module.
 */

use Drupal\Core\Render\Element\Textfield;

/**
 * Implements hook_element_info().
 */
function daterangepicker_element_info() {
  $types = array();
  
  $types['daterangepicker'] = [
    '#input' => TRUE,
    '#empty_value' => '',
    '#DateRangePicker_options' => [
      'initial_text' => t('Select date range...'),
      'apply_button_text' => t('Apply'),
      'clear_button_text' => t('Clear'),
      'cancel_button_text' => t('Cancel'),
      'range_splitter' => ' - ',
      'date_format' => 'd M, yy',
      'alt_format' => 'yy-mm-dd',
      'date_picker_options' => [
        'numberOfMonths' => 2,
      ],
    ],
    '#process' => ['daterangepicker_element_process'],
    // '#element_validate' => ['daterangepicker_element_validate'],
    '#attached' => [
      'library' => [
        'daterangepicker/daterange_picker',
      ],
    ],
  ];

  return $types;
}

/**
 * Add a basic textfield element and ensure moment.js is loaded.
 */
function daterangepicker_element_process(array &$element, FormStateInterface $form_state, FormInterface $form) {
  $options = $element['#DateRangePicker_options'];
  $element['range'] = [
    '#type' => Textfield::class,
    '#required' => ($element['#delta'] == 0 && $element['#required']) ? $element['#required'] : FALSE,
    '#attributes' => [
      'class' => [
        'daterangepicker',
      ],
    ],
    '#attached' => [
      'library' => [
        'daterangepicker/daterange_picker',
      ],
      'drupalSettings' => [
        'daterangepicker' => [
          'defaultValue' => isset($element['#default_value']) ? $element['#default_value'] : '',
          'initialText' => $options['initial_text'],
          'applyButtonText' => $options['apply_button_text'],
          'clearButtonText' => $options['clear_button_text'],
          'cancelButtonText' => $options['cancel_button_text'],
          'rangeSplitter' => $options['range_splitter'],
          'dateFormat' => $options['date_format'],
          'altFormat' => $options['alt_format'],
          'datepickerOptions' => $options['date_picker_options'],
        ],
      ],
    ],
  ];
  return $element;
}
// function daterangepicker_element_process($element, &$form_state, $form) {
//   $options = $element['#DateRangePicker_options'];
//   $element['range'] = array(
//     '#type' => 'textfield',
//     '#required' => ($element['#delta'] == 0 && $element['#required']) ? $element['#required'] : FALSE,
//     '#attributes' => array(
//       'class' => array(
//         'daterangepicker',
//       ),
//     ),
//     '#attached' => array(
//       'js' => array(
//         array(
//           'data' => array(
//             'daterangepicker' => array(
//               'defaultValue' => isset($element['#default_value']) ? $element['#default_value'] : '',
//               'initialText' => $options['initial_text'],
//               'applyButtonText' => $options['apply_button_text'],
//               'clearButtonText' => $options['clear_button_text'],
//               'cancelButtonText' => $options['cancel_button_text'],
//               'rangeSplitter' => $options['range_splitter'],
//               'dateFormat' => $options['date_format'],
//               'altFormat' => $options['alt_format'],
//               'datepickerOptions' => $options['date_picker_options'],
//             ),
//           ),
//           'type' => 'setting',
//         ),
//       ),
//     ),
//   );

//   libraries_load('moment');
//   return $element;
// }
// function daterangepicker_element_validate(&$element, &$form_state) {
//   if ($element['#required'] && empty($form_state['values'][$element['#name']])) {
//     // @TODO: improve the validation error message display.
//     // As the plugin hides the textfield and adds its own thing, the validation
//     // error gets stripped out, we need to either add the right classes to the
//     // plugins generated control or to guess the plugin id/class and add the
//     // error there.
//     $message = t('!name field is required.', array('!name' => $element['#name']));
//     drupal_set_message($message);
//     form_error($element,$message );
//   }
// }

/**
 * Implements hook_library().
 */
// function daterangepicker_library() {
//   $info = [];
//   $library_path = drupal_get_path('module', 'daterangepicker');
//   // // jQuery Date Range Picker plugin.
//   // $info['jquery-ui-daterangepicker'] = [
//   //   'title' => 'jQuery UI DateRangePicker',    
//   //   'website' => 'http://tamble.github.io/jquery-ui-daterangepicker',    
//   //   'version' => '0.4.3',    
//   //   'js' => [
//   //     $library_path . '/jquery.comiseo.daterangepicker.min.js' => ['group' => 'library'],
//   //   ],
//   //   'css' => [      
//   //     $library_path . '/jquery.comiseo.daterangepicker.css' => [],
//   //   ],
//   //   'dependencies' => [      
//   //     ['system', 'ui'],
//   //     ['system', 'ui.button'],
//   //     ['system', 'ui.widget'],
//   //     ['system', 'ui.position'],
//   //     ['system', 'ui.menu'],
//   //     ['system', 'ui.datepicker'],
//   //   ],
//   // ];

//   $module_path = drupal_get_path('module', 'daterangepicker');
//   $info['drupal.daterangepicker'] = [    
//     'title' => 'Drupal DateRangePicker integration',    
//     'website' => 'https://drupal.org/project/daterangepicker',    
//     'version' => '1.0',    'js' => [      
//       $module_path . '/js/daterangepicker.js' => [        
//         'group' => JS_DEFAULT,        
//         'weight' => 100,      
//       ],
//     ],
//     // Add some css so it looks a little better by default.
//     'css' => [      
//       $module_path . '/css/daterangepicker.css' => [],
//     ],
//     'dependencies' => [      
//       ['daterangepicker', 'jquery-ui-daterangepicker'],
//     ],
//   ];

//   return $info;
// }
// function daterangepicker_library() {
//   $info = array();
//   $library_path = daterangepicker_get_library_path();
//   // jQuery Date Range Picker plugin.
//   $info['jquery-ui-daterangepicker'] = array(
//     'title' => 'jQuery UI DateRangePicker',
//     'website' => 'http://tamble.github.io/jquery-ui-daterangepicker',
//     'version' => '0.4.3',
//     'js' => array(
//       $library_path . '/jquery.comiseo.daterangepicker.min.js' => array('group' => 'JS_LIBRARY'),
//     ),
//     'css' => array(
//       $library_path . '/jquery.comiseo.daterangepicker.css' => array(),
//     ),
//     'dependencies' => array(
//       array('system', 'ui'),
//       array('system', 'ui.button'),
//       array('system', 'ui.widget'),
//       array('system', 'ui.position'),
//       array('system', 'ui.menu'),
//       array('system', 'ui.datepicker'),
//     ),
//   );

//   $module_path = drupal_get_path('module', 'daterangepicker');
//   $info['drupal.daterangepicker'] = array(
//     'title' => 'Drupal DateRangePicker integration',
//     'website' => 'https://drupal.org/project/daterangepicker',
//     'version' => '1.0',
//     'js' => array(
//       $module_path . '/js/daterangepicker.js' => array(
//         'group' => JS_DEFAULT,
//         'weight' => 100,
//       ),
//     ),
//     // Add some css so it looks a little better by default.
//     'css' => array(
//       $module_path . '/css/daterangepicker.css' => array(),
//     ),
//     'dependencies' => array(
//       array('daterangepicker', 'jquery-ui-daterangepicker'),
//     ),
//   );

//   return $info;
// }

/**
 * Get the location of the Date range picker library.
 *
 * @return bool|string
 *  The location of the library, or FALSE if the library isn't installed.
 */
// function daterangepicker_get_library_path() {
//   if (function_exists('libraries_get_path')) {
//     return libraries_get_path('daterangepicker');
//   }

//   // The following logic is taken from libraries_get_libraries()
//   $searchdir = array();

//   // Similar to 'modules' and 'themes' directories inside an installation
//   // profile, installation profiles may want to place libraries into a
//   // 'libraries' directory.
//   $searchdir[] = 'profiles/' . drupal_get_profile() . '/libraries';

//   // Always search sites/all/libraries.
//   $searchdir[] = 'sites/all/libraries';

//   // Also search sites/<domain>/*.
//   $searchdir[] = conf_path() . '/libraries';

//   foreach ($searchdir as $dir) {
//     if (file_exists($dir . '/daterangepicker/jquery.comiseo.daterangepicker.min.js')) {
//       return $dir . '/daterangepicker';
//     }
//   }

//   return FALSE;
// }
