<?php
/**
 * @file
 * Date range picker module.
 */

/**
 * Implements hook_theme().
 */
function daterangepicker_theme($existing, $type, $theme, $path) {

  return [
    'daterangepicker' => [
      'variables' => [
        'DateRangePickerOptions' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function daterangepicker_library_info_alter(&$libraries, $module) {
  if ($module == 'daterangepicker') {
    // In case that the libraries are included locally, use those instead of the
    // CDN.
    // @see https://www.drupal.org/node/3099614
    $library_file_finder = \Drupal::service('library.libraries_directory_file_finder');
    $current_libraries = [
      'jquery_ui_daterange_picker' => 'jquery.comiseo.daterangepicker.min.js',
      'moment' => 'moment.min.js',
      'jquery_ui' => 'jquery-ui.min.js',
    ];
    foreach ($current_libraries as $current_library_id => $current_library_file) {
      echo $library_file_finder->find('composer.json');
      if (isset($libraries[$current_library_id])) {
        $path = $library_file_finder->find($current_library_file);
        if ($path) {
          $libraries[$current_library_id]['js'] = [
            '/' . $path => ['minified' => TRUE]
          ];
        }
      }
    }

    // Include style files.
    $libraries_styles = [
      'jquery_ui_daterange_picker' => 'jquery.comiseo.daterangepicker.css',
      'jquery_ui' => 'jquery-ui.min.css',
    ];
    foreach ($current_libraries as $current_library_id => $current_library_file) {
      if (isset($libraries[$current_library_id])) {
        $path = $library_file_finder->find($current_library_file);
        if ($path) {
          $libraries[$current_library_id]['css'] = [
            'theme' => [
              '/' . $path => []
            ]
          ];
        }
      }
    }
  }
}

